version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
            name: checkout submodules
            command: |
              git submodule init
              git submodule update --remote
      - run:
          name: setup
          command: |
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

            # Install build-essential, curl
            $SUDO apt-get update
            $SUDO apt-get install -y build-essential curl

            # Install premake5
            curl -L -o premake.tar.gz "https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz"
            $SUDO tar -xzf premake.tar.gz && rm premake.tar.gz
            $SUDO mv premake5 /usr/bin/premake5
      - run:
          name: prebuild
          command: |
            cd ~/project/test/
            premake5 gmake
      - run:
          name: build
          command: |
            cd ~/project/test/project/
            make